// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uofwebcxqmcbilxejgmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZndlYmN4cW1jYmlseGVqZ21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTc5NzgsImV4cCI6MjA1ODI5Mzk3OH0.7_f3-EFJJz6kBdB1nrLGJSRCtNlcrduzo4lSw_jpmQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);